services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.10-py3
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    command:
      - tritonserver
      - --model-repository=/models
      - --model-control-mode=explicit
      - --strict-model-config=false
      - --http-port=8003
      - --grpc-port=8004
      - --metrics-port=8005
    ports:
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
    volumes:
      - /tmp/triton-deploy/model_repository:/models
    restart: unless-stopped
