-- 模块12 缺陷修复：接入配置条目增加平台名称列与在线状态探测结果列。
ALTER TABLE gb28181_access_configs ADD COLUMN IF NOT EXISTS name VARCHAR(64);
ALTER TABLE gb28181_access_configs ADD COLUMN IF NOT EXISTS online_status VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE gb28181_access_configs ADD COLUMN IF NOT EXISTS last_check_at TIMESTAMPTZ;

ALTER TABLE ga1400_access_configs ADD COLUMN IF NOT EXISTS name VARCHAR(64);
ALTER TABLE ga1400_access_configs ADD COLUMN IF NOT EXISTS online_status VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE ga1400_access_configs ADD COLUMN IF NOT EXISTS last_check_at TIMESTAMPTZ;
