<template>
  <section class="content review-wide media-alarm-page">
    <div class="review-titlebar"><div><h1>告警联动</h1><p>通过探测器采集环境、入侵和人车布控报警信号，并联动视频、录像、声音、大屏和客户端提示</p></div><button class="btn primary" @click="showToast('告警联动规则已模拟刷新')">刷新告警</button></div>
    <div class="media-alarm-layout">
      <aside class="panel media-alarm-sidebar"><div class="media-side-menu"><button v-for="tab in alarmTabs" :key="tab.key" :class="{ active: activeAlarmTab === tab.key }" @click="activeAlarmTab = tab.key">{{ tab.label }}</button></div><input class="input" placeholder="搜索探测器/区域/车牌" aria-label="搜索告警" /><div class="media-ptz-section"><div class="media-panel-head"><b>告警类型</b><span class="status-pill reject">高危 4</span></div><div class="media-alarm-category"><button class="active"><span>环境数据</span><em>12</em></button><button><span>非法入侵</span><em>8</em></button><button><span>异常人车布控</span><em>5</em></button><button><span>设备异常</span><em>3</em></button></div></div><div class="media-ptz-section"><div class="media-panel-head"><b>实时告警队列</b><button class="link-blue">清空</button></div><ul class="media-alarm-queue"><li class="critical"><b>周界入侵</b><span>A区东侧围栏 · 12:42:18</span></li><li><b>烟感浓度异常</b><span>B2机房 · 12:38:09</span></li><li><b>布控车辆出现</b><span>北门卡口 · 12:31:44</span></li><li><b>温湿度越限</b><span>档案室 · 12:25:30</span></li></ul></div></aside>
      <main class="media-alarm-main"><div class="media-summary-row"><div class="media-summary-item"><b>28</b><span>今日告警</span></div><div class="media-summary-item"><b>9</b><span>待处理</span></div><div class="media-summary-item"><b>16</b><span>已联动视频</span></div><div class="media-summary-item"><b>4</b><span>大屏上墙</span></div></div>
        <section v-if="activeAlarmTab === 'monitor'" class="panel media-alarm-panel"><div class="media-alarm-monitor-grid"><div><div class="media-alarm-video"><img :src="store.img.car" alt="周界入侵告警画面" /><div class="media-alarm-overlay"><b>周界入侵告警</b><span>A区东侧围栏 12:42:18</span><span>联动摄像机：周界球机 IPC-03</span></div></div><div class="media-alarm-actions" style="margin-top:10px;"><button class="btn primary">客户端弹窗</button><button class="btn" @click="setRoute('mediaWall')">上墙显示</button><button class="btn">播放告警声音</button><button class="btn" @click="setRoute('mediaPlayback')">打开录像</button><button class="btn" @click="openModal('alarmEventDetail')">查看详情</button></div></div><aside><div class="media-panel-head"><b>联动执行结果</b><span class="status-pill pass">已触发</span></div><ol class="media-linkage-steps"><li class="done">接收探测器联动信号</li><li class="done">匹配报警规则：周界入侵联动</li><li class="done">客户端弹出实时画面并叠加文字</li><li class="done">电视墙窗口 1 开窗显示</li><li>自动关联前后 30 秒录像</li></ol><div class="config-note" style="margin-top:18px;"><strong>声音联动</strong><span>alarm_intrusion.wav · 音量 76%</span></div></aside></div></section>
        <section v-else-if="activeAlarmTab === 'detectors'" class="panel media-alarm-panel"><div class="media-wall-toolbar"><div class="media-control-buttons"><button class="btn primary" @click="openModal('detector')">＋ 新增探测器</button><button class="btn" @click="openModal('detector')">编辑</button><button class="btn">批量启用</button></div><div class="media-control-buttons"><input class="input" style="width:190px;" placeholder="请输入探测器名称" /><select class="select"><option>全部类型</option><option>环境数据</option><option>非法入侵</option><option>人车布控</option></select></div></div><div class="media-wall-table-wrap" style="margin-top:12px;"><table class="prototype-table media-wall-table" style="min-width:900px;"><thead><tr><th>探测器名称</th><th>类型</th><th>所在区域</th><th>采集数据</th><th>联动摄像机</th><th>状态</th><th>操作</th></tr></thead><tbody><tr><td>B2机房温湿度探测器</td><td>环境数据</td><td>B区 / B2栋</td><td>温度 32.6℃ / 湿度 76%</td><td>B2机房 IPC</td><td><span class="status-pill waiting">越限</span></td><td><button class="link-blue" @click="openModal('detector')">编辑</button></td></tr><tr><td>A区东侧红外对射</td><td>非法入侵</td><td>A区周界</td><td>入侵触发</td><td>周界球机 IPC-03</td><td><span class="status-pill reject">告警</span></td><td><button class="link-blue" @click="openModal('detector')">编辑</button></td></tr><tr><td>北门车辆布控探测</td><td>异常人车布控</td><td>北门卡口</td><td>车牌 黑A12345</td><td>北门卡口 IPC-07</td><td><span class="status-pill pass">在线</span></td><td><button class="link-blue" @click="openModal('detector')">编辑</button></td></tr></tbody></table></div></section>
        <section v-else-if="activeAlarmTab === 'rules'" class="panel media-alarm-panel"><div class="media-wall-toolbar"><div class="media-control-buttons"><button class="btn primary" @click="openModal('linkageRule')">＋ 新增联动规则</button><button class="btn" @click="openModal('linkageRule')">编辑规则</button><button class="btn danger">批量删除</button></div><span class="hint-text">报警信号触发后自动联动视频、录像、声音、大屏和客户端提示</span></div><div class="media-wall-table-wrap" style="margin-top:12px;"><table class="prototype-table media-wall-table" style="min-width:920px;"><thead><tr><th>规则名称</th><th>触发信号</th><th>联动视频</th><th>联动动作</th><th>叠加文字</th><th>状态</th><th>操作</th></tr></thead><tbody><tr><td>周界入侵联动</td><td>红外对射 / 入侵</td><td>周界球机 IPC-03</td><td>上墙、弹窗、录像、声音</td><td>周界入侵告警</td><td><span class="status-pill pass">开启</span></td><td><button class="link-blue" @click="openModal('linkageRule')">编辑</button></td></tr><tr><td>环境越限联动</td><td>温湿度 / 越限</td><td>B2机房 IPC</td><td>弹窗、录像、声音</td><td>机房环境异常</td><td><span class="status-pill pass">开启</span></td><td><button class="link-blue" @click="openModal('linkageRule')">编辑</button></td></tr><tr><td>布控车辆联动</td><td>车辆黑名单</td><td>北门卡口 IPC-07</td><td>上墙、弹窗、抓拍</td><td>布控车辆出现</td><td><span class="status-pill reject">关闭</span></td><td><button class="link-blue" @click="openModal('linkageRule')">编辑</button></td></tr></tbody></table></div></section>
        <section v-else class="panel media-alarm-panel"><div class="video-device-filter"><label>开始时间<input class="input" type="datetime-local" value="2026-07-09T00:00" /></label><label>结束时间<input class="input" type="datetime-local" value="2026-07-09T23:59" /></label><label>报警类型<select class="select"><option>全部</option><option>环境数据</option><option>非法入侵</option><option>异常人车布控</option></select></label><label>处理状态<select class="select"><option>全部</option><option>待处理</option><option>已确认</option><option>已关闭</option></select></label><button class="btn primary">查询</button></div><div class="media-wall-table-wrap"><table class="prototype-table media-wall-table" style="min-width:860px;"><thead><tr><th>报警时间</th><th>报警名称</th><th>报警类型</th><th>区域</th><th>联动结果</th><th>处理状态</th><th>操作</th></tr></thead><tbody><tr><td>2026-07-09 12:42:18</td><td>周界入侵</td><td>非法入侵</td><td>A区东侧围栏</td><td>上墙成功 / 录像已关联</td><td><span class="status-pill waiting">待处理</span></td><td><button class="link-blue" @click="openModal('alarmEventDetail')">详情</button></td></tr><tr><td>2026-07-09 12:38:09</td><td>烟感浓度异常</td><td>环境数据</td><td>B2机房</td><td>客户端弹窗 / 声音已播放</td><td><span class="status-pill pass">已确认</span></td><td><button class="link-blue" @click="openModal('alarmEventDetail')">详情</button></td></tr></tbody></table></div></section>
      </main>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "MediaAlarmPage",
  props: ["store", "state", "selectedVersion", "selectedDeployTask", "selectedEvent", "selectedAlgorithm"],
  inject: ["openModal", "setRoute", "showToast"],
  data() {
    return {
      activeAlarmTab: "monitor",
      alarmTabs: [
        { key: "monitor", label: "实时告警" },
        { key: "detectors", label: "探测器管理" },
        { key: "rules", label: "联动规则" },
        { key: "query", label: "报警查询" }
      ]
    };
  }
});
</script>
